import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { projectTitle } from '@/config'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{projectTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex justify-center items-center font-semibold text-6xl h-screen w-screen fixed"}>
        Test
      </div>
      <div className={"translate-y-3/4 w-screen h-screen bg-slate-200"}>
        Hello
      </div>
    </>
  )
}
